version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip && sudo apt-get install python-dev && sudo apt-get install python-pip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Configure AWS-CLI
          command: aws --version
      - run:
          name: Working Directory
          command: |
            pwd
            ls -al
      - run:
          name: Setup Node Application
          command: npm install
      - run:
          name: Run Tests
          command: npm test      