version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip && sudo apt-get install python-dev && sudo apt-get install python-pip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Configure AWS-CLI
          command: aws --version    
      - run:
          name: Zip Artifact
          command: |
            pwd
            ls -al
            mkdir codedeploy_artifact
            cp codedeploy/*.sh ./codedeploy_artifact/
            cp codedeploy/*.yml ./codedeploy_artifact/
            cp -r ./webapp ./codedeploy_artifact/
            cd codedeploy_artifact/
            pwd
            ls -al
            cd ..
            zip -r codedeploy_artifact-$CIRCLE_BUILD_NUM.zip ./codedeploy_artifact >/dev/null
            ls -al
            mkdir finalbuild
            mv codedeploy_artifact-$CIRCLE_BUILD_NUM.zip ./finalbuild
            cd finalbuild
            ls -al
            cd ..
            pwd
            ls -al
      - run:
          name: Deploy to S3
          command: aws s3 sync ./finalbuild/codedeploy_artifact-$CIRCLE_BUILD_NUM.zip  s3://csye6225-circleci-lab/ --delete
deployment:
  staging:
    branch: master
    codedeploy:
      codedeploy-application:
        application_root: /finalbuild
        revision_location:
          revision_type: S3
          s3_location:
            bucket: csye6225-circleci-lab
            key_pattern: codedeploy_artifact-$CIRCLE_BUILD_NUM.zip
        region: us-east-1
        deployment_group: codedeploy-dg
